networks:
  rgb:
    name: rgb

services:

  red:
    image: "emjunior/color-app:sb"
    environment:
      COLOR: "red"
    networks:
      rgb:
        aliases:
          - red

  green:
    image: "emjunior/color-app:sb"
    environment:
      COLOR: "green"
    networks:
      rgb:
        aliases:
          - green

  blue:
    image: "emjunior/color-app:sb"
    environment:
      COLOR: "blue"
    networks:
      rgb:
        aliases:
          - blue

  nginx:
    image: "nginx:1.25.2-alpine"
    ports:
      - "80:80"
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - rgb
